version: '0.1'

services:
  server:
    build:
      context: ./bot
      target: final
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BLIZZARD_CLIENT_ID=${BLIZZARD_CLIENT_ID}
      - BLIZZARD_CLIENT_SECRET=${BLIZZARD_CLIENT_SECRET}
      - BOT_PORT=${BOT_PORT:-8080}
      - DATABASE_URL=/app/data/bot.db
    ports:
      - "${BOT_PORT:-8080}:8080"
    volumes:
      - bot-data:/app/data
    depends_on:
      - updater
    restart: unless-stopped

  updater:
    build:
      context: ./db_updater
    environment:
      - DATABASE_URL=/app/data/bot.db
      - BLIZZARD_CLIENT_ID=${BLIZZARD_CLIENT_ID}
      - BLIZZARD_CLIENT_SECRET=${BLIZZARD_CLIENT_SECRET}
    volumes:
      - bot-data:/app/data
    restart: unless-stopped

volumes:
  bot-data:
