name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push bot image
        uses: docker/build-push-action@v5
        with:
          context: ./bot
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wow-discord-bot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wow-discord-bot:${{ github.sha }}

      - name: Build and push updater image
        uses: docker/build-push-action@v5
        with:
          context: ./db_update
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wow-discord-bot-updater:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wow-discord-bot-updater:${{ github.sha }}